### ISSUE TITLE
IE11 error: Multiple definitions of a property not allowed in strict mode

### ISSUE THREAD

**Issue by NPC** [wessberg/node.parentelement#1]
Hi,

I tried using this polyfill from NPM (https://www.npmjs.com/package/node.parentelement), and in IE11 (exactly where I need it) it doesn't load, console showing the following error:

SCRIPT1046: Multiple definitions of a property not allowed in strict mode
node.parentelement.min.js (1,314)

If I remove "use strict", the file now loads, but still parentElement is not added to non-Element nodes. I'll continue investigating this tomorrow, but perhaps you have an idea what could be wrong?

**Comment by wessberg** [comment]
Fixed by https://github.com/wessberg/node.parentelement/issues/2
